<# 
PrivFox
Version: 0.0.3

A simple privacy helper for Firefox profiles.

What this does:
- Finds Firefox profiles in %APPDATA%\Mozilla\Firefox\Profiles
- Creates/updates user.js in each profile
- Backs up an existing user.js before changing it
- Disables Mozilla telemetry, studies/experiments, crash report upload,
  Firefox Suggest / QuickSuggest sponsored suggestions, trending suggestions,
  and search suggestions.

How to use:
1. Close Firefox completely.
2. Right-click this file and choose "Run with PowerShell".
   If Windows blocks scripts, open PowerShell in this folder and run:
   powershell -ExecutionPolicy Bypass -File .\privfox.ps1
3. Start Firefox again.

To undo:
- Open your Firefox profile folder.
- Delete user.js, or restore the backup user.js.backup-YYYYMMDD-HHMMSS.

Contact:
byaldon@proton.me

Disclaimer:
PrivFox is an independent project. It is not affiliated with, endorsed by,
or sponsored by Mozilla or Firefox. Firefox is a trademark of the Mozilla Foundation.
#>

$ErrorActionPreference = "Stop"
$PrivFoxVersion = "0.0.3"

Write-Host ""
Write-Host "PrivFox $PrivFoxVersion" -ForegroundColor Cyan
Write-Host "-------------" -ForegroundColor Cyan
Write-Host "A simple privacy helper for Firefox profiles."
Write-Host ""

# Check Firefox profiles folder
$profilesRoot = Join-Path $env:APPDATA "Mozilla\Firefox\Profiles"

if (-not (Test-Path $profilesRoot)) {
    Write-Host "Could not find Firefox profiles folder:" -ForegroundColor Red
    Write-Host $profilesRoot
    Write-Host ""
    Write-Host "Is Firefox installed and has it been opened at least once?"
    Read-Host "Press Enter to exit"
    exit 1
}

# Warn if Firefox is running
$firefoxProcesses = Get-Process firefox -ErrorAction SilentlyContinue
if ($firefoxProcesses) {
    Write-Host "Firefox appears to be running." -ForegroundColor Yellow
    Write-Host "Please close Firefox completely before continuing."
    Write-Host ""
    $answer = Read-Host "Continue anyway? Type YES to continue"
    if ($answer -ne "YES") {
        Write-Host "Cancelled. Close Firefox and run the script again."
        Read-Host "Press Enter to exit"
        exit 0
    }
}

# Settings to write to user.js
# Firefox reads user.js on startup and applies these preferences to prefs.js.
$settings = @"
// PrivFox Firefox privacy preferences
// Generated by privfox.ps1
// PrivFox version: $PrivFoxVersion
// Close Firefox before editing this file.

// Mozilla data collection / telemetry
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.usage.uploadEnabled", false);

user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.coverage.opt-out", true);
user_pref("toolkit.coverage.opt-out", true);
user_pref("toolkit.coverage.endpoint.base", "");

// Studies / Shield / experiments
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");
user_pref("experiments.enabled", false);
user_pref("experiments.supported", false);
user_pref("network.allow-experiments", false);

// Crash reports
user_pref("breakpad.reportURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.crashReports.unsubmittedCheck.enabled", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);

// Firefox Suggest / QuickSuggest / sponsored suggestions
user_pref("browser.urlbar.quicksuggest.enabled", false);
user_pref("browser.urlbar.suggest.quicksuggest", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", false);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.merino.enabled", false);
user_pref("browser.urlbar.merino.endpointURL", "");

// Trending/search suggestions in address bar
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.trending.featureGate", false);
user_pref("browser.urlbar.suggest.trending", false);

// New tab sponsored/recommended content
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);

// Keep normal top sites enabled for usability, while sponsored top sites remain disabled.
user_pref("browser.newtabpage.activity-stream.feeds.topsites", true);

user_pref("browser.newtabpage.activity-stream.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry.structuredIngestion", false);

// Extension recommendations
user_pref("browser.discovery.enabled", false);
user_pref("extensions.getAddons.showPane", false);
user_pref("extensions.htmlaboutaddons.recommendations.enabled", false);
"@

$profileDirs = Get-ChildItem -Path $profilesRoot -Directory

if (-not $profileDirs) {
    Write-Host "No Firefox profile folders found." -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$changedCount = 0
$verifiedCount = 0
$failedProfiles = @()

foreach ($profile in $profileDirs) {
    $profilePath = $profile.FullName
    $userJsPath = Join-Path $profilePath "user.js"

    Write-Host "Profile found:" -ForegroundColor Green
    Write-Host "  $profilePath"

    try {
        if (Test-Path $userJsPath) {
            $backupPath = Join-Path $profilePath "user.js.backup-$timestamp"
            Copy-Item -Path $userJsPath -Destination $backupPath -Force
            Write-Host "  Existing user.js backed up as:"
            Write-Host "  $backupPath"
        }

        # ASCII is sufficient for user.js and avoids encoding/BOM compatibility issues.
        Set-Content -Path $userJsPath -Value $settings -Encoding ASCII -Force
        $changedCount++

        # Verify that the file exists and contains several core PrivFox preferences.
        if (-not (Test-Path $userJsPath)) {
            throw "user.js was not created."
        }

        $writtenContent = Get-Content -Path $userJsPath -Raw
        $requiredChecks = @(
            'user_pref("datareporting.healthreport.uploadEnabled", false);',
            'user_pref("toolkit.telemetry.enabled", false);',
            'user_pref("app.shield.optoutstudies.enabled", false);',
            'user_pref("browser.urlbar.quicksuggest.enabled", false);'
        )

        foreach ($requiredSetting in $requiredChecks) {
            if (-not $writtenContent.Contains($requiredSetting)) {
                throw "Verification failed: a required setting is missing from user.js."
            }
        }

        $verifiedCount++
        Write-Host "  user.js updated and verified." -ForegroundColor Cyan
        Write-Host ""
    }
    catch {
        $failedProfiles += $profilePath
        Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host ""
    }
}

Write-Host "------------------------------------------------------------"
if ($failedProfiles.Count -eq 0 -and $verifiedCount -gt 0) {
    Write-Host "SUCCESS" -ForegroundColor Green
    Write-Host "$verifiedCount Firefox profile(s) updated and verified."
    Write-Host ""
    Write-Host "Next steps:"
    Write-Host "1. Start Firefox."
    Write-Host "2. Open about:config if you want to verify a setting manually."
    Write-Host "3. Search for: datareporting.healthreport.uploadEnabled"
    Write-Host ""
    Write-Host "To undo this, delete user.js or restore the backup file."
    exit 0
}
else {
    Write-Host "FAILED" -ForegroundColor Red
    Write-Host "$verifiedCount profile(s) succeeded; $($failedProfiles.Count) profile(s) failed."
    if ($failedProfiles.Count -gt 0) {
        Write-Host ""
        Write-Host "Failed profile(s):"
        foreach ($failedProfile in $failedProfiles) {
            Write-Host "  $failedProfile"
        }
    }
    Write-Host ""
    Write-Host "No success is reported unless user.js was actually written and verified."
    exit 1
}
