#!/usr/bin/env bash
# PrivFox
# Version: 0.0.2
#
# A simple privacy helper for Firefox profiles on Linux.
#
# What this does:
# - Finds Firefox profiles in common Linux Firefox profile locations
# - Creates/updates user.js in each profile
# - Backs up an existing user.js before changing it
# - Disables Mozilla telemetry, studies/experiments, crash report upload,
#   Firefox Suggest / QuickSuggest sponsored suggestions, trending suggestions,
#   and search suggestions.
#
# How to use:
# 1. Close Firefox completely.
# 2. Open a terminal in this folder.
# 3. Run:
#      chmod +x ./privfox.sh
#      ./privfox.sh
# 4. Start Firefox again.
#
# To undo:
# - Open your Firefox profile folder.
# - Delete user.js, or restore the backup user.js.backup-YYYYMMDD-HHMMSS.
#
# Contact:
# byaldon@proton.me
#
# Disclaimer:
# PrivFox is an independent project. It is not affiliated with, endorsed by,
# or sponsored by Mozilla or Firefox. Firefox is a trademark of the Mozilla Foundation.

set -euo pipefail

PRIVFOX_VERSION="0.0.2"

printf '\n\033[36mPrivFox %s\033[0m\n' "$PRIVFOX_VERSION"
printf '\033[36m-------------\033[0m\n'
printf 'A simple privacy helper for Firefox profiles.\n\n'

# Common Firefox profile locations on Linux:
# - Regular Firefox package: ~/.mozilla/firefox
# - Snap Firefox package: ~/snap/firefox/common/.mozilla/firefox
# - Flatpak Firefox package: ~/.var/app/org.mozilla.firefox/.mozilla/firefox
PROFILE_ROOTS=(
    "$HOME/.mozilla/firefox"
    "$HOME/snap/firefox/common/.mozilla/firefox"
    "$HOME/.var/app/org.mozilla.firefox/.mozilla/firefox"
)

# Warn if Firefox appears to be running.
if command -v pgrep >/dev/null 2>&1; then
    if pgrep -x firefox >/dev/null 2>&1 || pgrep -x firefox-bin >/dev/null 2>&1; then
        printf '\033[33mFirefox appears to be running.\033[0m\n'
        printf 'Please close Firefox completely before continuing.\n\n'
        read -r -p 'Continue anyway? Type YES to continue: ' answer
        if [[ "$answer" != "YES" ]]; then
            printf 'Cancelled. Close Firefox and run the script again.\n'
            exit 0
        fi
        printf '\n'
    fi
fi

SETTINGS=$(cat <<EOF
// PrivFox Firefox privacy preferences
// Generated by privfox.sh
// PrivFox version: $PRIVFOX_VERSION
// Close Firefox before editing this file.

// Mozilla data collection / telemetry
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.usage.uploadEnabled", false);

user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.coverage.opt-out", true);
user_pref("toolkit.coverage.opt-out", true);
user_pref("toolkit.coverage.endpoint.base", "");

// Studies / Shield / experiments
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");
user_pref("experiments.enabled", false);
user_pref("experiments.supported", false);
user_pref("network.allow-experiments", false);

// Crash reports
user_pref("breakpad.reportURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.crashReports.unsubmittedCheck.enabled", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);

// Firefox Suggest / QuickSuggest / sponsored suggestions
user_pref("browser.urlbar.quicksuggest.enabled", false);
user_pref("browser.urlbar.suggest.quicksuggest", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", false);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.merino.enabled", false);
user_pref("browser.urlbar.merino.endpointURL", "");

// Trending/search suggestions in address bar
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.trending.featureGate", false);
user_pref("browser.urlbar.suggest.trending", false);

// New tab sponsored/recommended content
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);

// Keep normal top sites enabled for usability, while sponsored top sites remain disabled.
user_pref("browser.newtabpage.activity-stream.feeds.topsites", true);

user_pref("browser.newtabpage.activity-stream.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry.structuredIngestion", false);

// Extension recommendations
user_pref("browser.discovery.enabled", false);
user_pref("extensions.getAddons.showPane", false);
user_pref("extensions.htmlaboutaddons.recommendations.enabled", false);
EOF
)

profile_dirs=()

for root in "${PROFILE_ROOTS[@]}"; do
    if [[ -d "$root" ]]; then
        while IFS= read -r -d '' dir; do
            base_name="$(basename "$dir")"
            if [[ -f "$dir/prefs.js" || "$base_name" == *default* || "$base_name" == *profile* ]]; then
                profile_dirs+=("$dir")
            fi
        done < <(find "$root" -mindepth 1 -maxdepth 1 -type d -print0)
    fi
done

if [[ ${#profile_dirs[@]} -eq 0 ]]; then
    printf '\033[31mCould not find any Firefox profile folders.\033[0m\n\n'
    printf 'Checked these locations:\n'
    for root in "${PROFILE_ROOTS[@]}"; do
        printf '  %s\n' "$root"
    done
    printf '\nIs Firefox installed and has it been opened at least once?\n'
    exit 1
fi

timestamp="$(date +%Y%m%d-%H%M%S)"
changed_count=0

for profile_path in "${profile_dirs[@]}"; do
    user_js_path="$profile_path/user.js"

    printf '\033[32mProfile found:\033[0m\n'
    printf '  %s\n' "$profile_path"

    if [[ -f "$user_js_path" ]]; then
        backup_path="$profile_path/user.js.backup-$timestamp"
        cp "$user_js_path" "$backup_path"
        printf '  Existing user.js backed up as:\n'
        printf '  %s\n' "$backup_path"
    fi

    printf '%s\n' "$SETTINGS" > "$user_js_path"
    printf '\033[36m  user.js updated.\033[0m\n\n'
    changed_count=$((changed_count + 1))
done

printf '\033[32mDone.\033[0m\n'
printf '%s Firefox profile(s) updated.\n\n' "$changed_count"
printf 'Next steps:\n'
printf '1. Start Firefox.\n'
printf '2. Open about:config if you want to verify the settings.\n'
printf '3. Search for: datareporting.healthreport.uploadEnabled\n\n'
printf 'To undo this, delete user.js from your Firefox profile folder or restore the backup.\n'
