#!/bin/bash
# PrivFox
# Version: 0.0.2

VERSION="0.0.2"
FIREFOX_DIR="$HOME/.mozilla/firefox"

echo -e "\e[36mPrivFox $VERSION (Linux)\e[0m"
echo -e "\e[36m-------------\e[0m"
echo "A simple privacy helper for Firefox profiles."
echo ""

if [ ! -d "$FIREFOX_DIR" ]; then
    echo -e "\e[31mCould not find Firefox profiles folder:\e[0m"
    echo "$FIREFOX_DIR"
    echo ""
    echo "Is Firefox installed and has it been opened at least once?"
    exit 1
fi

if pgrep -x "firefox" > /dev/null || pgrep -x "firefox-bin" > /dev/null; then
    echo -e "\e[33mFirefox appears to be running.\e[0m"
    echo "Please close Firefox completely before continuing."
    echo ""
    read -p "Continue anyway? Type YES to continue: " answer
    if [ "$answer" != "YES" ]; then
        echo "Cancelled. Close Firefox and run the script again."
        exit 0
    fi
fi

SETTINGS=$(cat <<EOF
// PrivFox Firefox privacy preferences
// Generated by privfox.sh
// PrivFox version: $VERSION
// Close Firefox before editing this file.

// Mozilla data collection / telemetry
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.usage.uploadEnabled", false);

user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.coverage.opt-out", true);
user_pref("toolkit.coverage.opt-out", true);
user_pref("toolkit.coverage.endpoint.base", "");

// Studies / Shield / experiments
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");
user_pref("experiments.enabled", false);
user_pref("experiments.supported", false);
user_pref("network.allow-experiments", false);

// Crash reports
user_pref("breakpad.reportURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.crashReports.unsubmittedCheck.enabled", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);

// Firefox Suggest / QuickSuggest / sponsored suggestions
user_pref("browser.urlbar.quicksuggest.enabled", false);
user_pref("browser.urlbar.suggest.quicksuggest", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", false);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.merino.enabled", false);
user_pref("browser.urlbar.merino.endpointURL", "");

// Trending/search suggestions in address bar
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.trending.featureGate", false);
user_pref("browser.urlbar.suggest.trending", false);

// New tab sponsored/recommended content
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);

// Keep normal top sites enabled for usability, while sponsored top sites remain disabled.
user_pref("browser.newtabpage.activity-stream.feeds.topsites", true);

user_pref("browser.newtabpage.activity-stream.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry.structuredIngestion", false);

// Extension recommendations
user_pref("browser.discovery.enabled", false);
user_pref("extensions.getAddons.showPane", false);
user_pref("extensions.htmlaboutaddons.recommendations.enabled", false);
EOF
)

TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
CHANGED_COUNT=0

for PROFILE in "$FIREFOX_DIR"/*; do
    if [ -d "$PROFILE" ] && [[ $(basename "$PROFILE") == *.* ]]; then
        USER_JS="$PROFILE/user.js"
        
        echo -e "\e[32mProfile found:\e[0m"
        echo "  $PROFILE"

        if [ -f "$USER_JS" ]; then
            BACKUP_PATH="$PROFILE/user.js.backup-$TIMESTAMP"
            cp "$USER_JS" "$BACKUP_PATH"
            echo "  Existing user.js backed up as:"
            echo "  $BACKUP_PATH"
        fi

        echo "$SETTINGS" > "$USER_JS"
        echo -e "\e[36m  user.js updated.\e[0m\n"
        ((CHANGED_COUNT++))
    fi
done

if [ $CHANGED_COUNT -eq 0 ]; then
    echo -e "\e[31mNo Firefox profile folders found.\e[0m"
    exit 1
fi

echo -e "\e[32mDone.\e[0m"
echo "$CHANGED_COUNT Firefox profile(s) updated."
echo ""
echo "Next steps:"
echo "1. Start Firefox."
echo "2. Open about:config if you want to verify the settings."
echo "3. Search for: datareporting.healthreport.uploadEnabled"
echo ""
echo "To undo this, delete user.js from your Firefox profile folder or restore the backup."
